### ISSUE TITLE
Consider update to 1.13.3

### ISSUE THREAD

**Issue by trcoelho** [webjars/jquery-ui#35]
JQuery UI 1.13.3 was officially released on April 26, 2024 and is still not available at maven central:

https://mvnrepository.com/artifact/org.webjars/jquery-ui

Could you please consider also 1.13.3 version at maven central?

Thanks in advance.

**Comment by jamesward** [comment]
This will be released shortly.  Classic WebJars are released when someone asks.  This was the first request for `1.13.3` which is why the release didn't exist before now.
